name: appinio_video_player
description: A custom video player that builds on top of the official video_player package by flutter and adds many functionalities.
version: 1.3.0
homepage: https://github.com/appinioGmbH/flutter_packages
repository: https://github.com/appinioGmbH/flutter_packages

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_video_player_plus: ^4.0.4
  video_player: ^2.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0